project:
  type: website
  output-dir: docs

lang: en-US

website:
  title: "Interactive R Companion for SPSS Users"
  
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: session1.qmd
        text: "Session 1: Measurement"  
      - href: session3.qmd
        text: "Session 3: Descriptive Statistics"
    
  page-footer:
    left: "Interactive R Companion for SPSS Users"
    right: "Built with Quarto and webR"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: false
    code-tools: true
    css: styles.css

filters:
  - webr

webr:
  packages: 
    - "dplyr"
    - "tidyr" 
    - "ggplot2"
    - "stringr"
  autoload-packages: true

execute:
  echo: false
  warning: false
  message: false
