project:
  type: website
  output-dir: docs

lang: en-US

website:
  title: "Interactive R Companion for SPSS Users"
  
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: s01.qmd
        text: "Session01"
      - href: s02.qmd
        text: "S02"
      - href: s03.qmd
        text: "S03"
      - href: s04.qmd
        text: "S04"
      - href: s05.qmd
        text: "S05"
      - href: s06.qmd
        text: "S06"
      - href: s07.qmd
        text: "S07"
      - href: s08.qmd
        text: "S08"
      - href: s09.qmd
        text: "S09"
      - href: s10.qmd
        text: "S10"
      - href: s11.qmd
        text: "S11"
      - href: s12.qmd
        text: "S12"
    
  page-footer:
    left: "Instructor: Jan Hughes-Austin, PhD"
    right: "Assistant: D. Eastern Kang Sim, PhD"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: false
    code-tools: true
    css: styles.css

filters:
  - webr

webr:
  packages: 
    - "dplyr"
    - "tidyr" 
    - "ggplot2"
    - "stringr"
    - "broom"
    - "car"
    - "pwr"
    - "gtsummary"
  autoload-packages: true

execute:
  echo: false
  warning: false
  message: false
